apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-killer
  labels:
    app: job-killer
spec:
  replicas: 1
  template:
    metadata:
      name: job-killer
      labels:
        app: job-killer
    spec:
      containers:
        - name: job-killer
          image: ornew/job-killer
          imagePullPolicy: Always