apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-killer
  labels:
    app: job-killer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-killer
  template:
    metadata:
      name: job-killer
      labels:
        app: job-killer
    spec:
      containers:
        - name: job-killer
          image: ornew/job-killer
          imagePullPolicy: Always
          env:
          - name: SLACK_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                name: slack
                key: slack_webhook_url