apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  labels:
    app: job-killer
    job-killer: kill-me
spec:
  parallelism: 3
  template:
    metadata:
      labels:
        app: job-killer
    spec:
      containers:
      - name: test-job
        image: hello-world
      restartPolicy: Never